version: '3.1'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: sh -c "CGO_ENABLED=0 go test ./..."
    volumes:
      - ./:/go/src/github.com/AirHelp/zendesk-mock
    depends_on:
      - fmt
      - vet
  vet:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: go vet -v ./...
    volumes:
      - .:/go/src/github.com/AirHelp/zendesk-mock
  fmt:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: gofmt ./...
    volumes:
      - .:/go/src/github.com/AirHelp/zendesk-mock
